Werewolf Manager 2/Controllers/Werewolf/Setup/RoleInfoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Werewolf_Manager_2.Models.Werewolf.DBModels;
using Werewolf_Manager_2.Models.Werewolf.InfoManagers;

namespace Werewolf_Manager_2.Controllers.Werewolf.Setup
{
    public class RoleInfoController : Controller
    {
        // GET: RoleInfo
        public ActionResult Index()
        {
            return View(RoleInfoManager.RolesInformation);
        }

        public ActionResult Details(RoleType role)
        {
            return View(RoleInfoManager.RolesInformation.Where(rDI => rDI.RoleType == role).FirstOrDefault());
        }
    }
}

Werewolf Manager 2/Views/RoleInfo/Details.cshtml
@model Werewolf_Manager_2.Models.Werewolf.InfoManagers.RoleInfoManager.RoleDisplayInfo

@{  
    ViewBag.Title = Model.RoleName;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

<img src="@Url.Content(Model.ImagePath)" alt="Image" style="width:350px;height:350px" />
<br/>
<br/>
@Html.Label("Team") <br />
<p>@Model.Team.ToString()</p><br />

@Html.Label("Powers")<br />
<p>@Model.RoleDescription</p><br />

@Html.Label("Rulings")<br />
<p>@Model.RulingDescription</p><br />

@Html.Label("Victory Condition")<br />
<p>@Model.TeamDisplayInfo.TeamDescription</p><br />

@Html.Label("Villager Lover")<br />
<p>@Model.TeamDisplayInfo.VillageLoverDescription</p><br />

@Html.Label("Werewolf Lover")<br />
<p>@Model.TeamDisplayInfo.WerewolfLoverDescription</p><br />

@Html.Label("Serial Killer Lover")<br />
<p>@Model.TeamDisplayInfo.SerialKillerLoverDescription</p><br />

@Html.Label("Jester Lover")<br />
<p>@Model.TeamDisplayInfo.JesterLoverDescription</p><br />

<div>
    @Html.ActionLink("Back to Roles", "Index", "RoleInfo")
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Werewolf Manager 2/Views/RoleInfo/Index.cshtml
@model IEnumerable<Werewolf_Manager_2.Models.Werewolf.InfoManagers.RoleInfoManager.RoleDisplayInfo>

@{
    ViewBag.Title = "Roles";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

<table class="table">
    <tr>
        <th>
            Roles
        </th>        
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                <a href='@Url.Action("Details", "RoleInfo", new { role = item.RoleType })'>
                    <img src="@Url.Content(item.ImagePath)" alt="Image" style="width:350px;height:350px" />
                </a>                
            </td>            
        </tr>
    }
</table>

<div>
    @Html.ActionLink("Back to Games", "Index", "Games")
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}